changelog:
  categories:
    - title: 🚀 Features
      labels:
        - feat
    - title: 🐛 Fixes
      labels:
        - fix
    - title: 🧰 Maintenance
      labels:
        - chore
        - refactor
    - title: 📚 Docs
      labels:
        - docs